claude-code-bedrock-url: ENC[AES256_GCM,data:Ba49OWlK9ex/SH6XrLyZV7aAkI+dbvHD3227Ay/TqLusa2fhIoY3iYRWNWAyJc0p+Pb0KBS50U7ZqFP1NTuIyhWLGa/zCKSMjY7vhsDL1UgNutp3ovFt,iv:FddSK8Rp0TXAYQHtG6lSs15S245wH4jj27CTaB1Ig/8=,tag:JIqyR3OrYjR4uGWMkJLC9Q==,type:str]
claude-code-token: ENC[AES256_GCM,data:WwjDnZr13QVbiiNXmRKpEL9Z61wNXI6jbw==,iv:4jyueidfsifV0OoEMhviae8d3jXi4ZznnVuwE+p+B0Q=,tag:T3NH4ParHDDluxJJ7ug/kg==,type:str]
sops:
    age:
        - recipient: age18g65lsgudew4g2gzyvh6x3tm7k3eurx3el493t7q63p6hrvrrgtqefpmf2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSWRXbWRmSDBSU0pNT0pX
            MS84VXdSak4rNXoxTytlRFgzMTkzaVJMK3djCnRPNm1zLytHK0hCVjM0Q0dPUzNm
            WUZBRTd0ZG1MbUgxWEo5bkpweVFNY0UKLS0tIHVuT0JlVTNUTU1EWXp2U3pkc3ZC
            bXlVLzM0bmV3VVE1UWdBcDZ1V09yMlUKiFrGF2kb3IsryYm77iYhJW1gqCRtD6P1
            l3YJZnlhSVUZnYyQbBlKdSapQeI7MIdbW4xPA21wlO/HIpVdoL3NGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T02:46:18Z"
    mac: ENC[AES256_GCM,data:+x+y2NEuXvcHXTRAUhB0/T9AQpddM0WH5FQZ2PM3UkS9zFI5sHayu16I/u4Vs4sDOJAQT2Y3yR03/D/Fm8uX6Qk8ZvJTmvTHEGmZdbeow6D91VgKo+gec+lOJ86w3VpePTTxQWgqO9qfJgfsFFiDC/U+1kUkzvB/m3j88gneCOI=,iv:YwFz+ZdvOIEQcpgoQxTA42zBjI7jd7pATeHA4kXQFMI=,tag:84gaIl243kjAvsSL8goAKA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
